# Generated by Django 4.2.1 on 2023-06-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_ed_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ed_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='job_zone',
            field=models.IntegerField(blank=True, choices=[(1, 'Some High Schol'), (2, 'High School Diploma or GED'), (3, "Associate's Degree or Vocational School"), (4, "Bachelor's Degree"), (5, "Master's Degree or Higher")], default=1),
        ),
    ]
