# Generated by Django 4.2.1 on 2023-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0003_remove_testquestion_ans_remove_testquestion_op1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='trait_neg',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='trait_pos',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
