# Generated by Django 4.2.1 on 2023-05-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0004_testquestion_trait_neg_testquestion_trait_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('choices', models.IntegerField(blank=True, choices=[(-10, 'Strongly Dislike'), (-5, 'Dislike'), (0, 'Unsure'), (5, 'Like'), (10, 'Strongly Like')], default=0)),
                ('trait_pos', models.CharField(max_length=10, null=True)),
                ('trait_neg', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quiz_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptTest.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='TestMaster',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AptTest.quiz'),
        ),
    ]
