# Generated by Django 4.2.1 on 2023-05-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0008_remove_quiz_quiz_taker_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch1', models.CharField(max_length=200, null=True)),
                ('ch2', models.CharField(max_length=200, null=True)),
                ('ch3', models.CharField(max_length=200, null=True)),
                ('ch4', models.CharField(max_length=200, null=True)),
                ('ch5', models.CharField(max_length=200, null=True)),
                ('ch6', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='ch1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ch2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ch3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ch4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ch5',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AptTest.choices'),
        ),
    ]
