# Generated by Django 4.2.1 on 2023-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0015_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.JSONField(null=True),
        ),
    ]
