# Generated by Django 4.2.1 on 2023-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0025_remove_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trait_neg',
        ),
        migrations.AddField(
            model_name='quiz',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
