# Generated by Django 4.2.1 on 2023-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0028_alter_question_trait_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='career',
            name='holland_code',
        ),
        migrations.RemoveField(
            model_name='career',
            name='iq_min',
        ),
        migrations.RemoveField(
            model_name='career',
            name='tags',
        ),
        migrations.AddField(
            model_name='career',
            name='holland_code_scores',
            field=models.JSONField(default=dict),
        ),
    ]
