# Generated by Django 4.2.1 on 2023-06-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0029_rename_name_career_title_remove_career_holland_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
