# Generated by Django 4.2.1 on 2023-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0033_career_holland_code_as_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_zone',
            field=models.IntegerField(default=0),
        ),
    ]
