# Generated by Django 4.2.1 on 2023-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0034_career_job_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='work_activities',
            field=models.JSONField(default=dict),
        ),
    ]
