# Generated by Django 4.2.1 on 2023-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0035_career_work_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[(1, 'Holland Code'), (2, 'Job Zone'), (3, 'Work Activities'), (4, 'General Skills')], default=1),
        ),
    ]
