# Generated by Django 4.2.1 on 2023-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0038_alter_result_job_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Holland Code'), (2, 'Job Zone'), (3, 'Work Activities'), (4, 'General Skills')], default=1),
        ),
    ]
