# Generated by Django 4.2.1 on 2023-06-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0039_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='json_choices',
            field=models.JSONField(default=dict),
        ),
    ]
