# Generated by Django 4.2.1 on 2023-06-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0041_alter_result_job_zone_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=0, max_length=256, null=True),
        ),
    ]
