# Generated by Django 4.2.1 on 2023-06-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0042_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_choices',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
