# Generated by Django 4.2.1 on 2023-06-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0043_question_text_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text_choices',
        ),
    ]
