# Generated by Django 4.2.1 on 2023-06-15 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AptTest', '0044_remove_question_text_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='starter_questions',
            field=models.ManyToManyField(related_name='starter_questions', to='AptTest.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
