# Generated by Django 4.2.1 on 2023-06-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0045_quiz_starter_questions_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_of_qs_left',
            field=models.IntegerField(default=10),
        ),
    ]
