# Generated by Django 4.2.1 on 2023-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AptTest', '0048_result_work_activities_as_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='work_activities_as_perc',
            field=models.JSONField(default=dict),
        ),
    ]
